// See https://aka.ms/new-console-template for more information

using CodeGenSample;
using CP.Server.Embedded.COM.AutoGenerated;
using Nextended.Core.Attributes;

IMyUserDto c = MappingExtensions.ToCom(new User());

Console.WriteLine("Hello, World!");
