using Nextended.CodeGen.Attributes;
using Nextended.Core.Attributes;

namespace CodeGenSample;

[AutoGenerateCom]
public class SomethingThatHurts
{
    public string Name { get; set; }

    public string Secret { get; set; }
}


[AutoGenerateDto(Prefix = "My", Suffix = "Dto", IsComCompatible = true,ExplicitGenericImplementationTypes = new []{"string", "int"})]
public class User
{
    public string Name { get; set; }
    
    [IgnoreOnGeneration] 
    public string SecretDb { get; set; }
    
    [GenerationPropertySetting(PropertyName = "ThatUserAddress" //, Type = typeof(string)
    )]
    public Address Address { get; set; }
    
    [GenerationPropertySetting(PropertyName = "UserLevel")]
    public UserLevel? Level { get; set; }
}


[AutoGenerateDto(ToDtoMethodName = "ToMegaDto", IsComCompatible = true)]
public class Address
{
    public string Street { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
}

[AutoGenerateDto (IsComCompatible = true)]
public enum UserLevel
{
    Guest,
    User,
    Admin,
    [IgnoreOnGeneration]
    ServerAdmin,
}


public interface IInterface
{
    public string YG => "You got it!";
}