namespace Nextended.CodeGen.Attributes;

/// <summary>
/// Attribute to automatically generate a COM interface and a COM class for the class or enum it is applied to.
/// </summary>
public class AutoGenerateComAttribute : AutoGenerateDtoAttribute
{
    public AutoGenerateComAttribute(Type explicitGenericImplementations) : base(explicitGenericImplementations)
    {
        IsComCompatible = true;
        Prefix = "Com";
        Suffix = "";
    }

    public AutoGenerateComAttribute()
    {
        IsComCompatible = true;
        Prefix = "Com";
        Suffix = "";
    }
}