namespace Nextended.CodeGen.Attributes;

public class AutoGenerateComAttribute : AutoGenerateDtoAttribute
{
    public AutoGenerateComAttribute(Type genericTypeDescription) : base(genericTypeDescription)
    {
        IsComCompatible = true;
        Prefix = "Com";
        Suffix = "";
    }

    public AutoGenerateComAttribute()
    {
        IsComCompatible = true;
        Prefix = "Com";
        Suffix = "";
    }
}