using Nextended.CodeGen.Attributes;

namespace CodeGenSample.Entities.Base;

[AutoGenerateDto]
public class EntityBase: IDisposable
{
    public Guid Id { get; set; }
    public string ReferenceKey { get; set; }

    public void Dispose()
    {

    }
}