using Nextended.CodeGen.Attributes;

namespace CodeGenSample.Entities.Base;

[AutoGenerateDto]
public class EntityBase: IDisposable
{
    public Guid Id { get; set; }
    public string ReferenceKey { get; set; }

    public void Dispose()
    {

    }
}


[AutoGenerateDto(AutoGenerateDerived = true)]
public class AnotherBaseWhereDerivedAreAutoGenerated : EntityBase
{
    public string Name { get; set; }
}

public class DerivedEntity : AnotherBaseWhereDerivedAreAutoGenerated
{
    public string Description { get; set; }
    public string Title { get; set; }
}