using Nextended.Core.Attributes;
using Nextended.Core.Enums;
using YamlDotNet.Core.Tokens;

namespace CodeGenSample.Entities.Base;

[AutoGenerateDto(AutoGenerateDerived = true,
    KeepAttributesOnGeneratedClass = false,
    DefaultPropertyInterfaceAccess = InterfaceProperty.GetAndSet,
    KeepPropertyAttributesOnGeneratedClass = false,
    KeepPropertyAttributesOnGeneratedInterface = false)]
public class HubBaseGuidEntity : AuditedAggregateRoot<Guid>, IGuidEntity
{
  
}

public class AuditedAggregateRoot<TKey>
{
    public virtual TKey Id { get; protected set; }
}


public class Shipment : HubBaseGuidEntity
{
    public string TrackingNumber { get; set; }
    public DateTime ShippedDate { get; set; }
    public DateTime? DeliveredDate { get; set; }
    public Guid OrderId { get; set; }
}