//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nextended.Core.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nextended.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle unterstützten Dateiarten.
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is invalid to specify both a propertyToken (&apos;{0}&apos;) and a dataProperty element on a &apos;{1}&apos;.
        /// </summary>
        public static string BothPropertyTokenAndDataPropertyDefined {
            get {
                return ResourceManager.GetString("BothPropertyTokenAndDataPropertyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strg.
        /// </summary>
        public static string Ctrl {
            get {
                return ResourceManager.GetString("Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-4217-Code.
        /// </summary>
        public static string CurrencyISOCode {
            get {
                return ResourceManager.GetString("CurrencyISOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-4217-Code der Währung.
        /// </summary>
        public static string CurrencyISOCodeDescription {
            get {
                return ResourceManager.GetString("CurrencyISOCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.B GBP.
        /// </summary>
        public static string CurrencyISOCodeExample {
            get {
                return ResourceManager.GetString("CurrencyISOCodeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währungsname.
        /// </summary>
        public static string CurrencyName {
            get {
                return ResourceManager.GetString("CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Währung.
        /// </summary>
        public static string CurrencyNameDescription {
            get {
                return ResourceManager.GetString("CurrencyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.B. Pfund Sterling.
        /// </summary>
        public static string CurrencyNameExample {
            get {
                return ResourceManager.GetString("CurrencyNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nativer Name.
        /// </summary>
        public static string CurrencyNativeName {
            get {
                return ResourceManager.GetString("CurrencyNativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der native Name der Währung.
        /// </summary>
        public static string CurrencyNativeNameDescription {
            get {
                return ResourceManager.GetString("CurrencyNativeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.B Pounds of Sterling.
        /// </summary>
        public static string CurrencyNativeNameExample {
            get {
                return ResourceManager.GetString("CurrencyNativeNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol der Währung.
        /// </summary>
        public static string CurrencySymbolDescription {
            get {
                return ResourceManager.GetString("CurrencySymbolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.B £.
        /// </summary>
        public static string CurrencySymbolExample {
            get {
                return ResourceManager.GetString("CurrencySymbolExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------ASSERT--------.
        /// </summary>
        public static string DebugAssertBanner {
            get {
                return ResourceManager.GetString("DebugAssertBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----long Message-----.
        /// </summary>
        public static string DebugAssertLongMessage {
            get {
                return ResourceManager.GetString("DebugAssertLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----short Message-----.
        /// </summary>
        public static string DebugAssertShortMessage {
            get {
                return ResourceManager.GetString("DebugAssertShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Filter.
        /// </summary>
        public static string EmptyFilter {
            get {
                return ResourceManager.GetString("EmptyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der ISO-4217-Code muss genau 3 Stellen haben..
        /// </summary>
        public static string ISOCodeSizeError {
            get {
                return ResourceManager.GetString("ISOCodeSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkes Strg.
        /// </summary>
        public static string LeftCtrl {
            get {
                return ResourceManager.GetString("LeftCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; configuration section was found (&lt;section name=&apos;{0}&apos; type=&apos;{1}&apos; /&gt;)..
        /// </summary>
        public static string NoConfigurationSectionFound {
            get {
                return ResourceManager.GetString("NoConfigurationSectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtes Strg.
        /// </summary>
        public static string RightCtrl {
            get {
                return ResourceManager.GetString("RightCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhalt durchsuchen.
        /// </summary>
        public static string SearchContent {
            get {
                return ResourceManager.GetString("SearchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umsch.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; already exists in the token dictionary and cannot be added..
        /// </summary>
        public static string TokenAlreadyExists {
            get {
                return ResourceManager.GetString("TokenAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token cannot be a substring of another token. &apos;{0}&apos; is a substring of &apos;{1}&apos;.
        /// </summary>
        public static string TokenCannotBeSubstring {
            get {
                return ResourceManager.GetString("TokenCannotBeSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only specify one of format, type and dynamicProperty on a token element (token name=&apos;{0}&apos;).
        /// </summary>
        public static string TokenElementIncorrect {
            get {
                return ResourceManager.GetString("TokenElementIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; does not exist in the token dictionary..
        /// </summary>
        public static string UnrecognizedToken {
            get {
                return ResourceManager.GetString("UnrecognizedToken", resourceCulture);
            }
        }
    }
}
