using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Nextended.CodeGen.Config;
using Nextended.CodeGen.Contracts;
using Nextended.CodeGen.Helper;
using Nextended.Core.Attributes;
using Nextended.Core.Enums;

namespace Nextended.CodeGen.Generators.DtoGeneration;

/// <summary>
/// Emits a partial Riok.Mapperly mapper per type. Members and the [Mapper] attribute that the user declares
/// in an own part of the class win: the generator leaves them out.
/// </summary>
internal sealed class MapperlyMapperEmitter(DtoGenerationConfig config, DtoGenerationSymbols symbols, Compilation? compilation)
{
    public static string MapperName(INamedTypeSymbol type) => $"{type.Name}Mapper";

    public static bool CanUse(INamedTypeSymbol type, AutoGenerateDtoAttribute cfg)
        => cfg.MappingStrategy == DtoMappingStrategy.Mapperly
           && type.TypeKind != TypeKind.Enum && !type.IsGenericType && !type.IsAbstract;

    public GeneratedFile Emit(INamedTypeSymbol type, AutoGenerateDtoAttribute cfg, Dictionary<string, INamedTypeSymbol> dtoTypeDict, string ns, string? outputPath)
    {
        var name = MapperName(type);
        var fileName = $"{name}.g.cs";
        if (string.IsNullOrWhiteSpace(outputPath) || string.IsNullOrWhiteSpace(config.OutputPath))
            return new GeneratedFile(fileName, ns,
                $"#error Nextended.CodeGen: the Mapperly mapping of {type.Name} needs OutputPath and MappingOutputPath, Mapperly cannot see code that another source generator adds.\n",
                (string?)null);

        var (userMembers, userHasMapper) = UserPart($"{ns}.{name}", fileName);
        var modifier = cfg.ClassModifier.ToCSharpKeyword();
        var source = type.ToDisplayString();
        var dto = $"{symbols.GetNamespacePrefixString(cfg)}{DtoGenerationSymbols.GetDtoClassName(type, cfg, false)}";
        var props = symbols.GetDtoPropertiesDeep(type, symbols.Ignore).ToList();
        var renamed = props
            .Select(p => (Source: p.Name, Dto: DtoGenerationSymbols.GetDtoPropertyName(p, p.PropertyCfg(symbols))))
            .Where(p => p.Source != p.Dto)
            .ToList();
        var toDtoAttributes = renamed.Select(p => $"[MapProperty(\"{p.Source}\", \"{p.Dto}\")]").ToList();
        var toSourceAttributes = renamed.Select(p => $"[MapProperty(\"{p.Dto}\", \"{p.Source}\")]")
            .Concat(UnmappedSourceTargets(type, props).Select(n => $"[MapperIgnoreTarget(\"{n}\")]"))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendFileHeaderIf(config.CreateFileHeaders, fileName);
        sb.AppendLine("using Riok.Mapperly.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        if (!userHasMapper)
            sb.AppendLine("\t[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.Target)]");
        foreach (var mapper in ReferencedMappers(type, props, dtoTypeDict, ns))
            sb.AppendLine($"\t[UseStaticMapper(typeof({mapper}))]");
        sb.AppendLine($"\t{modifier} static partial class {name}");
        sb.AppendLine("\t{");

        void Method(string methodName, IEnumerable<string> attributes, string signature)
        {
            if (userMembers.Contains(methodName))
                return;
            foreach (var attribute in attributes)
                sb.AppendLine($"\t\t{attribute}");
            sb.AppendLine($"\t\t{modifier} static partial {signature};");
        }

        var toDto = DtoGenerationSymbols.GetToDtoMethodName(type, cfg);
        var toSource = DtoGenerationSymbols.GetToSourceMethodName(type, cfg);
        Method(toDto, toDtoAttributes, $"{dto} {toDto}(this {source} src)");
        Method(toSource, toSourceAttributes, $"{source} {toSource}(this {dto} src)");
        if (!userMembers.Contains("AssignTo"))
        {
            Method("AssignTo", toDtoAttributes, $"void AssignTo(this {source} src, [MappingTarget] {dto} dest)");
            Method("AssignTo", toSourceAttributes, $"void AssignTo(this {dto} src, [MappingTarget] {source} dest)");
        }

        sb.AppendLine("\t}");
        sb.AppendLine("}");
        return new GeneratedFile(fileName, ns, sb.ToString(), outputPath);
    }

    private (HashSet<string> Members, bool HasMapper) UserPart(string metadataName, string generatedFileName)
    {
        var existing = compilation?.GetTypeByMetadataName(metadataName);
        if (existing == null)
            return ([], false);

        bool IsUserCode(SyntaxReference? reference) =>
            reference != null && !string.Equals(Path.GetFileName(reference.SyntaxTree.FilePath), generatedFileName, StringComparison.OrdinalIgnoreCase);

        var members = new HashSet<string>(existing.GetMembers()
            .Where(m => m.DeclaringSyntaxReferences.Any(IsUserCode))
            .Select(m => m.Name), StringComparer.Ordinal);
        var hasMapper = existing.GetAttributes()
            .Any(a => a.AttributeClass?.Name == "MapperAttribute" && IsUserCode(a.ApplicationSyntaxReference));
        return (members, hasMapper);
    }

    private static IEnumerable<string> UnmappedSourceTargets(INamedTypeSymbol type, List<IPropertySymbol> dtoProps)
    {
        var mapped = new HashSet<string>(dtoProps.Select(p => p.Name), StringComparer.Ordinal);
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var t = type; t != null; t = t.BaseType)
            foreach (var p in t.GetMembers().OfType<IPropertySymbol>())
                if (!p.IsStatic && p.SetMethod is { DeclaredAccessibility: Accessibility.Public } && !mapped.Contains(p.Name) && seen.Add(p.Name))
                    yield return p.Name;
    }

    private IEnumerable<string> ReferencedMappers(INamedTypeSymbol type, List<IPropertySymbol> props, Dictionary<string, INamedTypeSymbol> dtoTypeDict, string ns)
    {
        var result = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var t in props.SelectMany(p => Walk(p.Type)))
        {
            var key = DtoGenerationSymbols.NormalizeForLookup(t).ToDisplayString();
            if (!dtoTypeDict.TryGetValue(key, out var target) || SymbolEqualityComparer.Default.Equals(target, type))
                continue;
            var targetCfg = target.ClassCfg(symbols);
            if (!targetCfg.GenerateMapping)
                continue;
            result.Add(CanUse(target, targetCfg) ? $"{ns}.{MapperName(target)}" : $"{ns}.MappingExtensions");
        }
        return result;
    }

    private static IEnumerable<ITypeSymbol> Walk(ITypeSymbol type)
    {
        yield return type;
        IEnumerable<ITypeSymbol> children = type switch
        {
            IArrayTypeSymbol array => new[] { array.ElementType },
            INamedTypeSymbol named => named.TypeArguments,
            _ => Array.Empty<ITypeSymbol>()
        };
        foreach (var child in children.SelectMany(Walk))
            yield return child;
    }
}
