using System.Text;

namespace Nextended.CodeGen.Helper;

internal static class StringBuilderHelper
{
    public static StringBuilder AppendIf(this StringBuilder sb, string value, bool condition = true)
    {
        if (condition)
            sb.Append(value);
        return sb;
    }

    public static StringBuilder AppendLineIf(this StringBuilder sb, string line, bool condition = true)
    {
        if (condition)
            sb.AppendLine(line);
        return sb;
    }
    public static StringBuilder AppendUsings(this StringBuilder sb, params string[] namespaces)
    {
        foreach (var ns in namespaces)
        {
            if (string.IsNullOrWhiteSpace(ns)) continue;
            sb.AppendLine($"using {ns};");
        }
        return sb;
    }

    public static StringBuilder CloseNamespace(this StringBuilder sb)
    {
        sb.AppendLine("}");
        return sb;
    }
    public static StringBuilder OpenNamespace(this StringBuilder sb, string @namespace)
    {
        sb.AppendLine($"namespace {@namespace} {{");
        return sb;
    }

    public static StringBuilder OpenRegion(this StringBuilder sb, string name, bool condition = true)
    {
        if (!condition)
            return sb;
        sb.AppendLine($"\t#region {name}");
        sb.AppendLine();
        return sb;
    }

    public static StringBuilder CloseRegion(this StringBuilder sb, string name, bool condition = true)
    {
        if (!condition)
            return sb;
        sb.AppendLine($"\t#endregion {name}");
        sb.AppendLine();
        return sb;
    }

    public static StringBuilder AppendFileHeader(this StringBuilder sb, params string[] names)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// --- AUTO GENERATED CODE ({DateTime.Now:G}) ---");
        foreach (var name in names) sb.AppendLine($"/// --- {name} ---");
        sb.AppendLine("/// </summary>\n");
        return sb;
    }

    public static StringBuilder AppendClassHeader(this StringBuilder sb, string className, string namespaceName, params string[] usings)
    {
        sb.AppendLine($"// <auto-generated /> ({DateTime.Now:G})");
        if (!usings.Any())
            usings = ["System", "Nextended.Core.Extensions"];
        sb.AppendUsings(usings);
        sb.AppendLine($"namespace {namespaceName} {{");
        sb.AppendLine($"\tpublic static partial class {className}");
        sb.AppendLine("\t{");

        return sb;
    }

}