namespace Nextended.Core.Attributes;

/// <summary>
/// Attribute to automatically generate a COM interface and a COM class for the class or enum it is applied to.
/// </summary>
public class AutoGenerateComAttribute : AutoGenerateDtoAttribute
{

    public AutoGenerateComAttribute()
    {
        IsComCompatible = true;
        Prefix = "Com";
        Suffix = "";
    }
}