using System.Reflection;
using System.Runtime.Loader;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Nextended.CodeGen.Config;
using Nextended.CodeGen.Contracts;
using Nextended.CodeGen.Generators.DtoGeneration;
using Nextended.Core.Attributes;
using Riok.Mapperly;
using Riok.Mapperly.Abstractions;
using Shouldly;

namespace Nextended.CodeGen.Tests;

[TestClass]
public class MapperlyMappingTests
{
    private const string Entities = """
        using System;
        using Nextended.Core.Attributes;
        using Nextended.Core.Enums;

        namespace Shop.Domain;

        public abstract class Entity
        {
            public Guid Id { get; protected init; } = Guid.NewGuid();
        }

        [AutoGenerateDto(Namespace = "Shop.Contracts")]
        public class Brand : Entity
        {
            public required string Name { get; set; }
            public Guid TenantId { get; set; }
        }

        [AutoGenerateDto(Namespace = "Shop.Contracts", MappingStrategy = DtoMappingStrategy.Mapperly)]
        public class Product : Entity
        {
            public required string Name { get; set; }
            public decimal Rate { get; set; }
            public Brand? Brand { get; set; }
            public Guid TenantId { get; set; }
        }
        """;

    private const string UserMapperPart = """
        using System;
        using Riok.Mapperly.Abstractions;
        using Shop.Contracts;
        using Shop.Domain;

        namespace Shop.Mapping;

        public static partial class ProductMapper
        {
            [MapProperty(nameof(Product.Rate), nameof(ProductDto.Rate), Use = nameof(RoundRate))]
            public static partial ProductDto ToDto(this Product src);

            [UserMapping(Default = false)]
            private static decimal RoundRate(decimal rate) => Math.Round(rate, 2);
        }
        """;

    private static DtoGenerationConfig Config(string? outputPath = "dtos/") => new()
    {
        Namespace = "Shop.Mapping",
        OutputPath = outputPath,
        MappingOutputPath = outputPath == null ? null : "mapping/",
        DeepProperties = true,
        PropertiesToIgnore = ["TenantId"],
        CreateFileHeaders = false
    };

    [TestMethod]
    public void Mapperly_mapper_leaves_out_what_the_user_part_declares()
    {
        var mapper = Generate(Compile(Entities, UserMapperPart), Config()).Single(f => f.FileName == "ProductMapper.g.cs");

        mapper.OutputPath.ShouldBe("mapping/");
        mapper.Content.ShouldContain("[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.Target)]");
        mapper.Content.ShouldContain("[UseStaticMapper(typeof(Shop.Mapping.MappingExtensions))]");
        mapper.Content.ShouldContain("[MapperIgnoreTarget(\"TenantId\")]");
        mapper.Content.ShouldContain("static partial Shop.Domain.Product ToNet(this Shop.Contracts.ProductDto src);");
        mapper.Content.ShouldNotContain(" ToDto(");
    }

    [TestMethod]
    public void Mapper_attribute_of_the_user_part_wins()
    {
        const string userPart = """
            using Riok.Mapperly.Abstractions;
            namespace Shop.Mapping;
            [Mapper]
            public static partial class ProductMapper;
            """;

        var mapper = Generate(Compile(Entities, userPart), Config()).Single(f => f.FileName == "ProductMapper.g.cs");

        mapper.Content.ShouldNotContain("[Mapper(");
        mapper.Content.ShouldContain(" ToDto(this Shop.Domain.Product src);");
    }

    [TestMethod]
    public void Mapperly_without_output_path_is_a_compile_error()
    {
        var mapper = Generate(Compile(Entities), Config(outputPath: null)).Single(f => f.FileName == "ProductMapper.g.cs");

        mapper.OutputPath.ShouldBeNull();
        mapper.Content.ShouldContain("#error");
    }

    [TestMethod]
    public void Generated_dtos_and_both_mapping_strategies_compile_and_map()
    {
        var compilation = Compile(Entities, UserMapperPart);
        var files = Generate(compilation, Config());
        files.Single(f => f.FileName == "BrandDto.g.cs").Content.ShouldContain("public required string Name { get; set; }");

        var withGenerated = compilation.AddSyntaxTrees(files.Select(f => Parse(f.Content, f.FileName)));
        Generate(withGenerated, Config()).Select(f => f.Content).ShouldBe(files.Select(f => f.Content));

        CSharpGeneratorDriver.Create(new MapperGenerator())
            .RunGeneratorsAndUpdateCompilation(withGenerated, out var final, out _);
        var problems = final.GetDiagnostics().Where(d => d.Severity >= DiagnosticSeverity.Warning).ToList();
        problems.ShouldBeEmpty(string.Join(Environment.NewLine, problems));

        var assembly = Load(final);
        var brand = New(assembly, "Shop.Domain.Brand", ("Name", "Acme"));
        var product = New(assembly, "Shop.Domain.Product", ("Name", "Hammer"), ("Rate", 9.999m), ("Brand", brand));

        var dto = Invoke(assembly, "Shop.Mapping.ProductMapper", "ToDto", product);
        Get(dto, "Name").ShouldBe("Hammer");
        Get(dto, "Rate").ShouldBe(10.00m);
        Get(dto, "Id").ShouldBe(Get(product, "Id"));
        Get(Get(dto, "Brand")!, "Name").ShouldBe("Acme");

        var back = Invoke(assembly, "Shop.Mapping.ProductMapper", "ToNet", dto);
        Get(back, "Name").ShouldBe("Hammer");
        Get(Get(back, "Brand")!, "Name").ShouldBe("Acme");
    }

    private static List<GeneratedFile> Generate(Compilation compilation, DtoGenerationConfig config)
        => new DtoGenerator(config).Execute(compilation).ToList();

    private static SyntaxTree Parse(string source, string path = "")
        => CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest), path);

    private static CSharpCompilation Compile(params string[] sources)
    {
        var references = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
            .Split(Path.PathSeparator)
            .Append(typeof(AutoGenerateDtoAttribute).Assembly.Location)
            .Append(typeof(MapperAttribute).Assembly.Location)
            .Distinct()
            .Select(p => MetadataReference.CreateFromFile(p));
        return CSharpCompilation.Create("Shop", sources.Select((s, i) => Parse(s, $"Source{i}.cs")), references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));
    }

    private static Assembly Load(Compilation compilation)
    {
        using var stream = new MemoryStream();
        var result = compilation.Emit(stream);
        result.Success.ShouldBeTrue(string.Join(Environment.NewLine, result.Diagnostics));
        stream.Position = 0;
        return new AssemblyLoadContext(null, isCollectible: true).LoadFromStream(stream);
    }

    private static object New(Assembly assembly, string type, params (string Name, object Value)[] values)
    {
        var instance = Activator.CreateInstance(assembly.GetType(type)!)!;
        foreach (var (name, value) in values)
            instance.GetType().GetProperty(name)!.SetValue(instance, value);
        return instance;
    }

    private static object Invoke(Assembly assembly, string type, string method, object argument)
        => assembly.GetType(type)!.GetMethods().Single(m => m.Name == method && m.GetParameters()[0].ParameterType == argument.GetType())
            .Invoke(null, [argument])!;

    private static object? Get(object instance, string property) => instance.GetType().GetProperty(property)!.GetValue(instance);
}
