using Microsoft.VisualStudio.TestTools.UnitTesting;
using Nextended.Core.Extensions;
using Nextended.Core.Tests.Models;

namespace Nextended.Core.Tests
{
    [TestClass]
    public class ReflectionPerformanceTests
    {
        /// <summary>
        /// This test demonstrates the current reflection-based mapping approach.
        /// Once the source generator is working, we'll compare performance.
        /// </summary>
        [TestMethod]
        public void ReflectionBasedMappingTest()
        {
            var person = new Person
            {
                Id = 1,
                Name = "John Doe",
                Age = 30,
                Email = "john@example.com"
            };

            // Current reflection-based approach
            var dto = person.MapTo<PersonDto>();

            Assert.AreEqual(person.Id, dto.Id);
            Assert.AreEqual(person.Name, dto.Name);
            Assert.AreEqual(person.Age, dto.Age);
            Assert.AreEqual(person.Email, dto.Email);
        }

        /// <summary>
        /// This test will be enabled once the source generator is working.
        /// It should demonstrate the same functionality with better performance.
        /// </summary>
        [TestMethod]
        [Ignore("Source generator mapping not yet implemented")]
        public void SourceGeneratorMappingTest()
        {
            var person = new Person
            {
                Id = 1,
                Name = "John Doe", 
                Age = 30,
                Email = "john@example.com"
            };

            // Future generated approach - this will be generated by the source generator
            // var dto = person.ToPersonDto();  // This method will be generated

            // For now, just validate the concept
            Assert.IsNotNull(person);
        }
    }
}