using CodeGenSample.Entities.Base;
using Nextended.CodeGen.Attributes;

namespace CodeGenSample.Entities;

[AutoGenerateDto(ToDtoMethodName = "ToMegaDto", ToSourceMethodName = "AsSrc", IsComCompatible = true
    ,Namespace = "MyGeneration"
)]
public class Address : EntityBase
{
    public string Street { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
}