using CodeGenSample.Entities.Base;
using Nextended.Core.Attributes;

namespace CodeGenSample.Entities;

[AutoGenerateDto(ToDtoMethodName = "ToMegaDto", ToSourceMethodName = "AsSrc", IsComCompatible = true
    ,Namespace = "MyGeneration", GenerateBeforeAndAfterAssignPartialsInMapping = true 
)]
public class Address : EntityBase
{
    public string Street { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
    public int Number { get; set; }
}