using Nextended.Core.Attributes;

namespace CodeGenSample.Entities;

[AutoGenerateDto]
public partial class Dimension<TUnit> : IDimension where TUnit : Unit
{
    public decimal? Value { get; set; }

    public virtual TUnit? Unit { get; set; }
    Unit? IDimension.Unit => Unit;


    public Dimension(decimal? value, TUnit? unit)
    {
        Value = value;
        Unit = unit;
    }
}


public interface IDimension
{
    // ReSharper disable once UnusedMemberInSuper.Global - getter can stay in here even though it isn't used in the interface
    decimal? Value { get; set; }
    Unit? Unit { get; }
}

[AutoGenerateDto]
public class Unit
{
    public decimal? BaseUnitFactor { get; set; }
    public decimal? NullPointShift { get; set; }
}

[AutoGenerateDto]
public class SuperUnit : Unit
{
}

[AutoGenerateDto]
public class ClassWithDimension
{
    public string Name { get; set; }
    public Dimension<SuperUnit> Dimension { get; set; }
}