using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Nextended.Core.Attributes;

namespace CodeGenSample.Entities
{
    [AutoGenerateDto(AutoGenerateDerived = true)]
    public abstract class GenericBaseClass<T>
    {
        public T Id { get; set; }
    }
    [AutoGenerateDto(AutoGenerateDerived = true)]
    public class DerivedGenericClass<T> : GenericBaseClass<T>
    {
        public string Name { get; set; }
    }
    [AutoGenerateDto(AutoGenerateDerived = true)]
    public class DerivedGenericClassWithInt : DerivedGenericClass<int>
    {

    }
}