using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CodeGenSample.Entities.Base;
using CodeGenSample.Entities.Enums;
using Nextended.Core.Attributes;
using Nextended.Core.Enums;

namespace CodeGenSample.Entities;



[JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
[AutoGenerateDto(Prefix = "My", Suffix = "Dto", IsComCompatible = false, 
    KeepAttributesOnGeneratedClass = true, 
    DefaultPropertyInterfaceAccess = InterfaceProperty.Get,
    KeepPropertyAttributesOnGeneratedClass = true, 
    KeepPropertyAttributesOnGeneratedInterface = true)]
public class User: EntityBase
{
    [MaxLength(3)]

    public string Name { get; set; }
    
    [IgnoreOnGeneration] 
    public string SecretDb { get; set; }
    
    [GenerationPropertySetting(PropertyName = "ThatUserAddress" //, Type = typeof(string)
    )]
    public Address Address { get; set; }
    
    [GenerationPropertySetting(PropertyName = "UserLevel", InterfaceAccess = InterfaceProperty.GetAndSet)]
    public UserLevel? Level { get; set; }

    public OtherInfos OtherInfos { get; set; }
}


public class OtherInfos
{
    public string Info1 { get; set; }
    public string Info2 { get; set; }
    public string Info3 { get; set; }
    public string Info4 { get; set; }
    public string Info5 { get; set; }
    public string Info6 { get; set; }
    public string Info7 { get; set; }
    public string Info8 { get; set; }
    public string Info9 { get; set; }
}