using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CodeGenSample.Entities.Base;
using CodeGenSample.Entities.Enums;
using Nextended.CodeGen.Attributes;
using Nextended.CodeGen.Enums;
using Nextended.Core.Attributes;

namespace CodeGenSample.Entities;



[JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
[AutoGenerateDto(Prefix = "My", Suffix = "Dto", IsComCompatible = false, 
    KeepAttributesOnGeneratedClass = true, 
    DefaultPropertyInterfaceAccess = InterfaceProperty.Get,
    KeepPropertyAttributesOnGeneratedClass = true, 
    KeepPropertyAttributesOnGeneratedInterface = true)]
public class User: EntityBase
{
    [MaxLength(3)]

    public string Name { get; set; }
    
    [IgnoreOnGeneration] 
    public string SecretDb { get; set; }
    
    [GenerationPropertySetting(PropertyName = "ThatUserAddress" //, Type = typeof(string)
    )]
    public Address Address { get; set; }
    
    [GenerationPropertySetting(PropertyName = "UserLevel", InterfaceAccess = InterfaceProperty.GetAndSet)]
    public UserLevel? Level { get; set; }
}