<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Shared.props" />

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Description>This Library provides great and usefull Extension Methods for caching</Description>
    <PackageTags>Cache</PackageTags>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Nextended.Core\Nextended.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="System.Runtime.Caching" />
  </ItemGroup>
  
</Project>
