// Generates the API reference pages for the documentation site.
//
// Source of truth is the *compiled* assembly, read through MetadataLoadContext, so the reference
// shows the surface that actually ships — including members that carry no XML doc comment. The XML
// documentation file next to the assembly supplies the summaries where they exist.
//
// Reading the DLL rather than the sources matters because CS1591 is suppressed in this repository:
// a source- or XML-only reference would silently omit every undocumented public member, which is
// exactly the gap this tool is meant to expose.
//
// Output (one file per package, per language):
//   docs/projects/<slug>-api.md
//   docs/de/projects/<slug>-api.md
//
// A companion report lists every public member with no summary, so the gaps can be filled:
//   artifacts/api-doc-gaps.md

using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Xml.Linq;

var repoRoot = FindRepoRoot();
var dataFile = Path.Combine(repoRoot, "docs", "data", "packages.json");
var packages = JsonNode.Parse(File.ReadAllText(dataFile))!["packages"]!.AsArray();

var checkOnly = args.Contains("-Check", StringComparer.OrdinalIgnoreCase);
var gaps = new List<string>();
var written = new List<string>();
var stale = new List<string>();
var problems = new List<string>();

foreach (var node in packages)
{
    var name = node!["name"]!.GetValue<string>();
    var slug = node["slug"]!.GetValue<string>();

    // Output.props puts the build under bin/<Package>/<TFM>/ and the XML doc one level up at
    // bin/<Package>/<Package>.xml. Pick the newest target framework so the reference describes the
    // most current surface; the -windows variants only exist for Nextended.UI.
    var packageBin = Path.Combine(repoRoot, "bin", name);
    var dll = Directory.Exists(packageBin)
        ? Directory.GetFiles(packageBin, $"{name}.dll", SearchOption.AllDirectories)
            .OrderByDescending(TargetFrameworkRank)
            .FirstOrDefault()
        : null;

    if (dll is null)
    {
        problems.Add($"{name}: no built assembly under bin/{name}/ — build the solution first.");
        continue;
    }

    var summaries = LoadXmlSummaries(Path.Combine(packageBin, $"{name}.xml"));
    var model = Api.Inspect(dll, name, summaries, gaps);

    foreach (var (lang, relative) in new[]
             {
                 ("en", Path.Combine("docs", "projects", $"{slug}-api.md")),
                 ("de", Path.Combine("docs", "de", "projects", $"{slug}-api.md")),
             })
    {
        var markdown = Api.Render(model, name, slug, lang);
        var path = Path.Combine(repoRoot, relative);
        var current = File.Exists(path) ? File.ReadAllText(path) : null;

        if (current == markdown) continue;

        if (checkOnly) { stale.Add(relative); continue; }

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, markdown, new UTF8Encoding(false));
        written.Add(relative);
    }
}

// ---------------------------------------------------------------------------
// The gap report is what makes the missing summaries actionable.
// ---------------------------------------------------------------------------
var gapReport = Path.Combine(repoRoot, "artifacts", "api-doc-gaps.md");
if (!checkOnly)
{
    Directory.CreateDirectory(Path.GetDirectoryName(gapReport)!);
    var sb = new StringBuilder()
        .AppendLine("# Public members without an XML summary")
        .AppendLine()
        .AppendLine("Generated by `tools/ApiRef`. Each line is a public member that ships without")
        .AppendLine("documentation, so the API reference shows it with no description.")
        .AppendLine()
        .AppendLine($"Total: {gaps.Count}")
        .AppendLine();
    foreach (var group in gaps.GroupBy(g => g.Split('\t')[0]).OrderBy(g => g.Key))
    {
        sb.AppendLine($"## {group.Key} ({group.Count()})").AppendLine();
        foreach (var line in group.Select(g => g.Split('\t')[1]).OrderBy(x => x))
            sb.AppendLine($"- `{line}`");
        sb.AppendLine();
    }
    File.WriteAllText(gapReport, sb.ToString(), new UTF8Encoding(false));
}

foreach (var p in problems) Console.Error.WriteLine($"WARNING: {p}");

if (checkOnly)
{
    foreach (var s in stale) Console.WriteLine($"STALE   {s}");
    if (stale.Count == 0 && problems.Count == 0)
    {
        Console.WriteLine("API reference pages are up to date.");
        return 0;
    }
    Console.WriteLine($"{stale.Count} stale, {problems.Count} problem(s). Run: dotnet run --project tools/ApiRef");
    return 1;
}

foreach (var w in written) Console.WriteLine($"updated {w}");
Console.WriteLine();
Console.WriteLine($"{written.Count} file(s) written, {gaps.Count} member(s) without a summary " +
                  $"(see artifacts/api-doc-gaps.md), {problems.Count} problem(s).");
return problems.Count > 0 ? 1 : 0;

// ---------------------------------------------------------------------------

static string FindRepoRoot()
{
    var dir = AppContext.BaseDirectory;
    while (dir is not null && !File.Exists(Path.Combine(dir, "Nextended.sln")))
        dir = Path.GetDirectoryName(dir);
    return dir ?? throw new InvalidOperationException("Nextended.sln not found above the tool.");
}

static Dictionary<string, string> LoadXmlSummaries(string xmlPath)
{
    var result = new Dictionary<string, string>(StringComparer.Ordinal);
    if (!File.Exists(xmlPath)) return result;

    foreach (var member in XDocument.Load(xmlPath).Descendants("member"))
    {
        var id = member.Attribute("name")?.Value;
        var summary = member.Element("summary");
        if (id is null || summary is null) continue;

        // Flatten <see cref="T:Ns.Type"/> and friends into readable inline code.
        var text = string.Concat(summary.Nodes().Select(Flatten));
        text = string.Join(' ', text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
        if (text.Length > 0) result[id] = text;
    }
    return result;

    static string Flatten(XNode n) => n switch
    {
        // VitePress compiles markdown as a Vue template, so a literal "<" in prose (someone wrote
        // List<T> without <see>) is parsed as an unclosed HTML tag and breaks the build. Escape it
        // here rather than in the renderer, so code produced by <see>/<c> keeps its backticks.
        XText t => t.Value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;"),
        XElement e when e.Name == "see" || e.Name == "paramref" || e.Name == "typeparamref" =>
            "`" + LastSegment(e.Attribute("cref")?.Value ?? e.Attribute("name")?.Value ?? e.Value) + "`",
        XElement e when e.Name == "c" || e.Name == "code" => "`" + e.Value.Trim() + "`",
        XElement e => string.Concat(e.Nodes().Select(Flatten)),
        _ => "",
    };

    static string LastSegment(string cref)
    {
        var v = cref.Contains(':') ? cref[(cref.IndexOf(':') + 1)..] : cref;
        var paren = v.IndexOf('(');
        if (paren >= 0) v = v[..paren];
        var dot = v.LastIndexOf('.');
        return dot >= 0 ? v[(dot + 1)..] : v;
    }
}

// Prefer the newest target framework: net10 > net9 > net8 > netstandard.
static int TargetFrameworkRank(string dllPath)
{
    var tfm = Path.GetFileName(Path.GetDirectoryName(dllPath)) ?? "";
    if (tfm.StartsWith("net10")) return 40;
    if (tfm.StartsWith("net9")) return 30;
    if (tfm.StartsWith("net8")) return 20;
    if (tfm.StartsWith("netstandard2.1")) return 11;
    if (tfm.StartsWith("netstandard")) return 10;
    return 0;
}
